version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nebula-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nebula}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nebula-network

  redis:
    image: redis:7-alpine
    container_name: nebula-redis
    ports:
      - "6379:6379"
    networks:
      - nebula-network

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: nebula-translate
    ports:
      - "5000:5000"
    environment:
      LT_LOAD_ONLY: en,es,fr,de,zh,ja,hi,ar
    networks:
      - nebula-network

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: nebula-whisper
    ports:
      - "9000:9000"
    environment:
      ASR_MODEL: base
      ASR_ENGINE: faster_whisper
    # Uncomment for GPU support:
    # runtime: nvidia
    networks:
      - nebula-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: nebula-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
      - redis
      - whisper
      - libretranslate
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    networks:
      - nebula-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: nebula-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nebula-network

volumes:
  postgres_data:

networks:
  nebula-network:
    driver: bridge